const actions = {
    LOGIN_REQUESTING: 'LOGIN_REQUESTING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    FETCH_AUTH_USER: 'FETCH_AUTH_USER',
    AUTHENTICATED: 'AUTHENTICATED',
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    SET_USER: 'SET_USER'
}

export default actions
